### ISSUE TITLE
fp16 error when running sahajbert participant snippet on Colab Pro

### ISSUE THREAD

**Issue by cdleong** [yandex-research/DeDLOC#3]
When running the snippet from the sahajbert example on Colab pro, I get this: 

```
ValueError: Mixed precision training with AMP or APEX (`--fp16`) and FP16 evaluation can only be used on CUDA devices.
```

But when I add this to the arguments, it goes away: 
```
--fp16 0
```

Should we update the snippet like so? 
```
HIVEMIND_THREADS=128 python run_trainer.py \
--output_dir ./outputs_trainer --overwrite_output_dir  --logging_dir ./logs_trainer \
--logging_first_step --logging_steps 100   --initial_peers COORDINATOR_IP:COORDINATOR_PORT \
--experiment_prefix NAME_YOUR_EXPERIMENT --seed 42 --averaging_timeout 120  --bandwidth 1000 \
--fp16 0
```

**Comment by mryab** [comment]
Judging by the `FP16 evaluation can only be used on CUDA device` part, I believe that Transformers can't detect that you are using a GPU. Are you sure you switched the runtime?

**Comment by cdleong** [comment]
🤦 ah, yeah. That would do it. Tested it out, and it works fine if _actually set it to have a GPU runtime_. 

I will leave my embarassing mistake up for future readers (https://xkcd.com/979/). Let it be known that you need to have a GPU for GPU-related things to work.
